#!/usr/local/opt/miniconda3/envs/common/bin/python
import argparse
import os
from report_rename import read_roster, batch_rename

dirname = os.path.dirname(__file__)


def read_args():
    parser = argparse.ArgumentParser(description='Report batch rename.')
    parser.add_argument('directory',
                        help='a directory under which files are to be renamed')
    parser.add_argument('--post', dest='postfix', default='',
                        help='suffix to be added to each file name')
    parser.add_argument('-e', dest='exceptions', default=[], nargs='+',
                        help="students who don't have to submit their reports")
    return parser.parse_args()


if __name__ == '__main__':
    args, roster = read_args(), read_roster()
    try:
        submitted = batch_rename(args.directory, args.postfix, roster)
        have_not_submitted = [x for x in roster
                              if x not in args.exceptions
                              and x not in submitted]
        for student_id in have_not_submitted:
            print(student_id + roster[student_id])
    except RuntimeError as message:
        print('RuntimeError: {}'.format(message))
